#ifndef TRADUCAO_H
#define TRADUCAO_H

typedef enum {
    //menu.c
    MSG_MENU_TITULO,
    MSG_MENU_OPCAO_NOVA_PARTIDA,
    MSG_MENU_OPCAO_CARREGAR_PARTIDA,
    MSG_MENU_OPCAO_AJUDA,
    MSG_MENU_OPCAO_SAIR,
    MSG_MENU_OPCAO_ESCOLHA_OPCAO,
    MSG_MENU_OPCAO_INVALIDA,
    MSG_MENU_FECHANDO_PROGRAMA,
    
    MSG_MENU_AJUDA_TITULO,
    MSG_MENU_AJUDA_LINHA1,
    MSG_MENU_AJUDA_LINHA2,
    MSG_MENU_AJUDA_LINHA3,
    MSG_MENU_AJUDA_LINHA4,
    MSG_MENU_AJUDA_LINHA5,
    MSG_MENU_AJUDA_LINHA6,


    //jogo.c
    MSG_JOGO_DIGITE_JOGADA,
    MSG_JOGO_SALVAR_SUCESSO,
    MSG_JOGO_SALVAR_ERRO,
    MSG_JOGO_DESISTENCIA,
    MSG_JOGO_COLUNA_ORIGEM_INVALIDA,
    MSG_JOGO_LINHA_ORIGEM_INVALIDA,
    MSG_JOGO_COLUNA_DESTINO_INVALIDA,
    MSG_JOGO_LINHA_DESTINO_INVALIDA,
    MSG_JOGO_SEPARADOR_COORDENADAS_INVALIDO,
    MSG_JOGO_FORMATO_COORDENADAS_INVALIDO,

    MSG_JOGO_PROMOCAO_PEAO_ESCOLHA_PECA,
    MSG_JOGO_PROMOCAO_PEAO_PECA_INVALIDA,

    MSG_JOGO_SALVAR_ERRO_ABERTURA_ARQUIVO,
    MSG_JOGO_CARREGAR_ERRO,

    MSG_JOGO_DIGITE_JOGADOR,
    MSG_JOGO_VEZ_JOGADOR,
    MSG_JOGO_MAIUSCULAS,
    MSG_JOGO_MINUSCULAS,
    MSG_JOGO_POSICAO_ORIGEM_VAZIA,

    MSG_JOGO_XEQUEMATE_REI_CAPTURADO_TITULO,
    MSG_JOGO_XEQUEMATE_VENCEDOR,
    MSG_JOGO_XEQUEMATE_PLACAR,
    MSG_JOGO_XEQUEMATE_TOTAL_MOVIMENTOS,
    MSG_JOGO_EMPATE_50MOVIMENTOS_TITULO,
    MSG_JOGO_XEQUEMATE_TITULO,
    MSG_JOGO_AFOGAMENTO_TITULO,
    MSG_JOGO_EMPATE_TEXTO,

    MSG_JOGO_JOGADA_INVALIDA,


    //jogadasvalidas.c
    MSG_JOGADAS_MOVIMENTO_MESMA_POSICAO,
    MSG_JOGADAS_PECA_MESMO_JOGADOR,
    MSG_JOGADAS_MOVER_PECA_OPONENTE,
    MSG_JOGADAS_DEIXA_REI_XEQUE,
    MSG_JOGADAS_MOVIMENTO_INVALIDO_PEAO,
    MSG_JOGADAS_MOVIMENTO_INVALIDO_TORRE,
    MSG_JOGADAS_MOVIMENTO_INVALIDO_CAVALO,
    MSG_JOGADAS_MOVIMENTO_INVALIDO_BISPO,
    MSG_JOGADAS_MOVIMENTO_INVALIDO_RAINHA,
    MSG_JOGADAS_MOVIMENTO_REI_XEQUE,
    MSG_JOGADAS_CASA_DESTINO_XEQUE,
    MSG_JOGADAS_MOVIMENTO_INVALIDO_REI,
    MSG_JOGADAS_PECA_INVALIDA,



    TOTAL_STRINGS //Apenas um indicador da quantidade.

} Texto;

typedef enum {
    PORTUGUES = 0,
    INGLES = 1,
    TOTAL_LINGUAS //Apenas um indicador da quantidade.
} Lingua;

void definirIdioma(Lingua novoIdioma);

const char* Msg(Texto ID_Texto);

#endif